timetable/autoupdate.py
Исправлена ошибка в 67 строке, когда создается таблица с неверными типами данных.
- [ x] Вы проверили свой код перед отправкой запроса?
=> fixing row 67

timetable/autoupdate.py
создание engine вынесено в таски.
- [x ] Вы проверили свой код перед отправкой запроса?
=> fix connection

timetable/autoupdate.py
Упрощены sql-запросы. Возможно это решить проблему доступа роли srvc_test_dwh к таблицам.
Теперь не удалюется и не переименовываются таблицы old, new, diff. Происходит только удаление данных из old, перенос данных из new в old, удаление данных из diff и добавление новых данных в diff
- [x ] Вы проверили свой код перед отправкой запроса?
=> possible solution to the problem: "must be owner of table", line 47.

timetable/autoupdate.py
line 84 fix.
- [ x] Вы проверили свой код перед отправкой запроса?
=> line 84 fix.

timetable/fetch.py
Добавлены новы страницы в расписании
- [x ] Вы проверили свой код перед отправкой запроса?
=> Changes in number of pages

timetable/autoupdate.py, timetable/fetch.py
Даги fetch.py и autoupdate соединены.
- [x ] Вы проверили свой код перед отправкой запроса?
=> New number of pages

timetable/autoupdate.py
- [ x] Вы проверили свой код перед отправкой запроса?
=> airflow Variables

union_members/fetch.py
Изменил логиру работы телеграм бота - теперь сообщение отправляется только при ошибке скачивания.
Убрал data_length из параметров функции.
Добавил параметр on_failure_callback и передал туда функцию отправки сообщения
Поменял текст сообщения
=> Изменение логики работы телеграм бота

timetable/fetch.py
Двиганул схему, убрал все лишнее
- Поправил стили
- Удалил лишние стейтменты
- Переместил схему
=> Fix timetable HTML fetcher

infra/logs.py
Удаляем логи, у которых create_ts больше трех дней назад
=> Truncate infra logs

infra/github.py
Пайплайны заливки данных об организации на гитхабе из REST API в DWH
=> Github STG

infra/github.py
- Теперь загружаются все данные, а не только первые 30 записей
- Добавил загрузку коммитов и задач из репозиториев
=> Better upload all, upload commits and issues

timetable_dwh/upload_to_dim.py
загружаю из профкомовского апи в dim_ справочники для дальнейшего использования
=> загружаю в справочники данные из апи

timetable_dwh/upload_to_dim.py
поменял тип поля group_number на str и заливаю
=> фикс заливки групп

timetable/mymsuapi_fetch.py
=> mymsufetch dag 

timetable/bulk_insert.py
=> Sleep addition + change batch delta to 100

union_members/union_member_data.py
Добавлен файл union_member_data.py содержащий ДАГ для заполнения таблицы с "ODS_INFO".info для корректировки формата данных "STG_USERDATA".info
Для использования SQL запроса я использовал PostgresOperator() который требует id подключения, настраиваемого в airflow
=> Added DAG with SQL to correct data format

union_members/union_member_data.py
Изменен формат дага:
Таск теперь вложенный в PostgresOperator, поправлены inlets outlets
Изменен SQL:
Простая вставка значений изменена на обновление данных за счет on conflict
=> SQL and DAG for ODS_INFO.info edited

union_members/union_member_data.py
added sql schema + DAG in order to fill ODS_INFO.info
=> dag to merge STG_AUTH + DWH_USERDATA

union_members/union_member_data.py
там не та sql схема была указана в даге
=> Dag for merging auth

timetable/parse.py
Новый даг для парсинга расписания из STG_RASPHYSMSU.raw_html
=> parse_raw_timetable_from_html

union_members/union_member_data.py
Меняет название ODS_USER.info на DWH_AUTH.user и добавляет колонку auth_email
=> DAG changed

pipelines/ods/timetable/link_timetable_cabinet/__init__.py, pipelines/ods/timetable/link_timetable_group/__init__.py, pipelines/ods/timetable/link_timetable_lecturer/__init__.py, pipelines/ods/timetable/link_timetable_lesson/__init__.py
Добавляю пайпалйны линка справочников и распаршенных данных из rasphysmsu
DISCLAIMER  про триграммы и метод поиска:
Тестовая версия, возможно потом сверю точнее
(сейчас это самый рабочий алгоритм)
https://github.com/profcomff/dwh-pipelines/issues/62
https://github.com/profcomff/dwh-pipelines/issues/61
https://github.com/profcomff/dwh-pipelines/issues/60
=> fill link tables

pipelines/dwh/rating/rating/comment.py, pipelines/dwh/rating/rating/lecturer.py, pipelines/ods/rating/rating/comment.py, pipelines/ods/rating/rating/lecturer.py, pipelines/ods/rating/rating/lecturer_user_comment.py
протягиваю таблички рейтинга + строю историю в scd2 чтобы смотреть апдейты по лекторам и комментам
Витрины после этого пра сделаю
=> add raging ods+dwh

pipelines/ods/marketing/__init__.py
=> marketing ods tables

pipelines/ods/marketing/__init__.py
=> fix ods marketing dag

pipelines/ods/marketing/__init__.py
=> Marketing add UUID gen

pipelines/stg/copy_api_tables/__init__.py
скопипастил из шаблона даг для перекачки табличек redirect api
Мне сказали, что скоро это можно будет протестить, чем пока что я не занимался
=> Added upload DAG for redirector

pipelines/common/get_vds_balance/__init__.py
Добавлен алерт на [один из дагов](https://airflow.profcomff.com/dags/check_vds_balance/grid?tab=code) для тестирования работы через глобальные переменные
=> Тестирование алертов на подопытном даге

pipelines/dm/marketing/__init__.py
=> service_stat_dag

pipelines/dm/marketing/__init__.py
=> Vlad branch

dags/dwh/user/info.py, dags/dwh/user/upsert.sql
Один даг перемещен в отдельную папку. Его структура изменена. Это нужно для тестирования новой структуры дагов.
=> reworked dwh user info dag

dags/dwh/user/info.py
Теперь во вкладке таски можно будет видеть ее sql. Это тестовая функция, поэтому пока что только для одного дага
=> task docs to dwh_user_info.info

dags/dwh/user/info.py
Забыл import os ну извините все мы люди куда без этого. Теперь будет работать 100% зуб даю
=> Fix import

.github/workflows/checks.yml
Был неправильно написан if из-за которого тесты не запускались
Также добавил нейминг в workflow файл
=> if statemant fixed + naming

.github/workflows/checks.yml
Убраны кавычки, вызывающие синт ошибку
=> invalid syntax fix

dags/common/get_vds_balance.py, plugins/api_utils/__init__.py, plugins/features/alert_message.py
Фиксит ошибку импорта grant_user_groups которая возникала из-за неполноты __init__ файла
Добавляет экранирование спецсимволов на dag_id и owner в алертах
Поправляет ссылку в алерте на кликабельную
=> Import err fix

dags/dm/marketing/frontend_actions_services.py, dags/dm/rating/dm_lecturer_comment_act.py, dags/dwh/rating/comment.py, dags/dwh/rating/lecturer.py, dags/ods/marketing/actions_info.py, dags/ods/rating/comment.py, dags/ods/rating/lecturer.py, dags/ods/rating/lecturer_user_comment.py, dags/stg/copy_api_tables/upload_api_marketing.py, dags/stg/copy_api_tables/upload_api_rating.py, dags/stg/copy_api_tables/upload_api_rental.py, plugins/features/alert_message.py
Раскатил алерты на некоторые даги
Поправил ссылку чтобы не было 404
=> alerts + link

dags/common/alert_tg/utils/fetch_comments.py
=> Fixup fetch_comments and add logs

dags/ods/rental/event.py, dags/ods/rental/event.sql, dags/ods/rental/item.py, dags/ods/rental/item.sql, dags/ods/rental/item_type.py, dags/ods/rental/item_type.sql, dags/ods/rental/rental_session.py, dags/ods/rental/rental_session.sql, dags/ods/rental/strike.py, dags/ods/rental/strike.sql
Добавлены даги на ods уровень рентала
=> rental-ods

dags/common/get_vds_balance.py
=> test-balance-fix

dags/common/alert_tg/config.py, dags/common/alert_tg/send_alert_pending_comments.py, dags/common/alert_tg/utils/fetch_comments.py, dags/common/alert_tg/utils/get_lecturer.py, dags/common/alert_tg/utils/get_userdata.py
Чисто тест нового формата сообщений
=> Develop new format

dags/dwh/user/info.py, dags/ods/user/info.py, dags/ods/user/info.sql, dags/stg/union_members/fetch.py
Фикс бага в получении юзер айди юнион мембер + даг для ods юзердаты с мэтчем юзердаты
=> Fetch userdata 

dags/ods/user/info.sql, dags/stg/union_members/fetch.py
=> Birthday fix

dags/ods/user/info.sql
добавлена логика мэтча по first_name и last_name
(вот бы научиться мэтчить только по full_name, а не этим мракобесием заниматься)
=> fix-first-name-last-name match

dags/ods/user/info.sql
=> day-bog-zarabotaet

dags/ods/user/info.sql
Изменен даг мэтчинга, теперь еще на ods userdata притягивается информация о проф билете
=> fix-match-with-card-table
